spring.application.name=api-gateway

server.port=${PORT:8086}


# ================================
# USER SERVICE
# ================================

spring.cloud.gateway.server.webflux.routes[0].id=user-service

spring.cloud.gateway.server.webflux.routes[0].uri=https://user-service-production-6fd7.up.railway.app

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**


# ================================
# PRODUCT SERVICE
# ================================

spring.cloud.gateway.server.webflux.routes[1].id=product-service

spring.cloud.gateway.server.webflux.routes[1].uri=https://product-service-production-1b6a.up.railway.app

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/products/**


# ================================
# CORS
# ================================

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=*

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true